# Loop functions and debugging

## lapply

lapply always returns a list, regardless of the input class

In [1]:
lapply

function (X, FUN, ...) 
{
    FUN <- match.fun(FUN)
    if (!is.vector(X) || is.object(X)) 
        X <- as.list(X)
    .Internal(lapply(X, FUN))
}
<bytecode: 0x0000000011f76fe0>
<environment: namespace:base>

In [2]:
x <- list(a = 1:5, b = rnorm(10))
x

$a
[1] 1 2 3 4 5

$b
 [1] -0.31602500  0.10709825 -0.38817674 -2.25233634 -0.01898979  0.83950497
 [7] -0.93165411 -0.18364772  1.88366131  0.80297883

In [3]:
# Returns the mean of each element in the list
lapply(x, mean)

$a
[1] 3

$b
[1] -0.04575863

In [4]:
lapply(1:4, runif)

[[1]]
[1] 0.5223603

[[2]]
[1] 0.7110750 0.6917275

[[3]]
[1] 0.8419268 0.3931754 0.9348420

[[4]]
[1] 0.9050622 0.3596434 0.8817100 0.9363287

In [5]:
runif

function (n, min = 0, max = 1) 
.Call(C_runif, n, min, max)
<bytecode: 0x000000001f78f038>
<environment: namespace:stats>

In [6]:
# Give input to the runif function

In [7]:
lapply(1:4, runif, min = 0, max = 10)

[[1]]
[1] 3.702124

[[2]]
[1] 5.888740 1.664134

[[3]]
[1] 8.794044 7.509959 8.242434

[[4]]
[1] 2.893332 4.477443 1.506569 1.292411

In [8]:
x <- list(a = matrix(1:4, 2), b = matrix(1:6, 3))
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

**NOTE TO SELF: **
lapply and friends make heavy use of anonymous functions

In [9]:
# Go through each matrix and spit out the first column. 
# Similar to lambda function
lapply(x, function(myMatrix) myMatrix[, 1])

$a
[1] 1 2

$b
[1] 1 2 3

## sapply

Will simplyfy the result of lapply if possible:
- If result is a list with one element, a vector is returned.
- If the result is a list with every element is a vector of same length, a matrix is returned.
- If it can't figure it out, a list is returned.

In [10]:
lapply(1:4, function(x) x**2)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

In [11]:
sapply(1:4, function(x) x**2)

[1]  1  4  9 16

### apply

Used to evaulate a function over the margins of an array:
- Over rows or columns in a matrix.
- Can be used with general arrays, e.g. taking the average of an array of matrices.
- Not really faster than writing a loop, but requires less typing.

In [12]:
str(apply)

function (X, MARGIN, FUN, ...)  


In [13]:
x <- matrix(rnorm(200), 20, 10)

In [14]:
apply(x, 2, mean) # Taking mean of the matrix columns

[1]  0.174573217 -0.051777861 -0.213726698 -0.022459375  0.144152890
 [6]  0.427077567  0.008029453  0.244661915 -0.299457246  0.028993467

In [15]:
apply(x, 1, sum) # Summing up the rows

[1]  2.3872437 -1.3545917 -2.3072427 -2.3207486  0.3313317 -0.4708911
 [7] -4.5035147  5.9232006  1.6119643  2.2200651  5.9025402 -1.7025699
[13]  6.7286205 -4.0263102 -0.5401954  2.0500811  2.0875686 -0.2663978
[19] -2.2853478 -0.6634593

## Shortcuts

For sums and means of a matrix, there exist some shortcuts:
- rowSums = apply(x, 1, sum)
- rowMeans = apply(x, 1, mean)
- colSums = apply(x, 2, sum)
- colMeans = apply(x, 2, mean)

They are faster and should be used for large matrices

In [16]:
x <- matrix(rnorm(200), 20, 10)
apply(x, 2, quantile, probs = c(0.25, 0.75)) # Applying the built-in quantile function and giving it input

[,1]       [,2]       [,3]       [,4]       [,5]      [,6]      [,7]
25% -0.5189913 -0.9131652 -0.5449028 -0.7495604 -0.5278997 -0.309002 -1.290599
75%  0.6973501  0.2725515  0.8300761  0.8745787  1.0007940  1.104798  0.939496
          [,8]       [,9]      [,10]
25% -0.1750097 -0.7457380 -0.6470574
75%  0.3653384  0.4036975  0.4443589

In [17]:
# Average matrix in array
a <- array(rnorm(2 * 2 * 3), c(2, 2, 3))
a
apply(a, c(1, 2), mean)

, , 1

          [,1]       [,2]
[1,]  1.540164 -1.7484925
[2,] -2.204588 -0.1579972

, , 2

           [,1]      [,2]
[1,] -0.2159778 0.2635617
[2,]  0.1722794 1.0628281

, , 3

           [,1]       [,2]
[1,] -1.1110439 -2.4663825
[2,] -0.7930769  0.3874574

[,1]       [,2]
[1,]  0.07104738 -1.3171044
[2,] -0.94179523  0.4307628

In [18]:
rowMeans(a, dims = 2)

[,1]       [,2]
[1,]  0.07104738 -1.3171044
[2,] -0.94179523  0.4307628

### mapply

In [19]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


In [20]:
first = 1:3
second = 2:4

func <- function(x, y) {
    x / y
}
# similar to c[func(1, 2), func(2, 3), func(3, 4)]
mapply(func, first, second)

[1] 0.5000000 0.6666667 0.7500000

### tapply

tapply is used to apply a function over a subset of a vector. Don't know why it's called tapply though.

In [21]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., simplify = TRUE)  


In [22]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10) # Generates a factor level vector (1, 2, 3), where each factor is repeated 10 times

In [23]:
f # Will use this to map to the data in x

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

In [24]:
# Take mean of each group
means <- tapply(x, f, mean)
means

ERROR: Error in dn[[2L]]: subscript out of bounds


1          2          3 
-0.2990282  0.4455419  1.2424978

In [25]:
for (m in means ) print(m) # Not sure why we get the error output above.

[1] -0.2990282
[1] 0.4455419
[1] 1.242498


In [26]:
mean(x[1:10]) # Same as the means[1]

[1] -0.2990282

### split
Takes a vector or other object and splits it into groups determined by a factor or list of factors

In [27]:
str(split)

function (x, f, drop = FALSE, ...)  


In [28]:
split(x, f)

$`1`
 [1] -1.3921632  0.0330471 -0.3703843  1.1326452 -1.0842884  0.6387839
 [7]  1.1477914  0.2241263 -2.4453293 -0.8745107

$`2`
 [1] 0.93541313 0.66609961 0.18055614 0.20273337 0.06518333 0.59925517
 [7] 0.39936495 0.45127181 0.61000708 0.34553426

$`3`
 [1]  2.3430195  0.9409727  1.4942748  0.2233704  1.0668563  1.9467585
 [7]  1.4897200  1.9358333  1.2199385 -0.2357659

In [29]:
lapply(split(x, f), mean) # Similar to what tapply performed. Returns back a list

$`1`
[1] -0.2990282

$`2`
[1] 0.4455419

$`3`
[1] 1.242498

### Splitting a data frame

In [30]:
library(datasets)

In [31]:
head(airquality)

Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6

In [32]:
s <- split(airquality, airquality$Month) # Create a dataframe for each month value (factor)

In [33]:
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [34]:
sout <- sapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm = TRUE))
sout

5         6          7          8         9
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

In [35]:
cor(sout["Ozone", ], sout["Wind", ])

[1] -0.9359046

## Debugging

Indication that something is wrong
- message : generic notification
- warning : indication that something is wrong but not fatal
- error : fatal error. execution stops
- condition : every point above is a condition. this is something programmers use to create own conditions

In [36]:
log(-1) # Warning, you get a number back, NaN

Warning message:
In log(-1): NaNs produced

[1] NaN

In [37]:
printmsg <- function(x) {
    if (x > 0) {
        print("x is greater than 0")
    } 
    else {
        print("x is less or equal to 0")
    }
    invisible(x)
}

printmsg2 <- function(x) {
    if (is.na(x)) {
        print("x is a missing values")
    }
    else if (x > 0) {
        print("x is greater than 0")
    } 
    else {
        print("x is less or equal to 0")
    }
    invisible(x) # Does not print out the returned value
}

In [38]:
printmsg(x = 3)
printmsg(NA) # We get an error now. Execution stops

[1] "x is greater than 0"


ERROR: Error in if (x > 0) {: missing value where TRUE/FALSE needed


In [39]:
printmsg2(NA)

[1] "x is a missing values"


In [40]:
# This is just an example
x <- log(-1)
printmsg2(x) # The function will now give you an answer, but log(-1) is not a good input.

Warning message:
In log(-1): NaNs produced

[1] "x is a missing values"


### Debugging tools in R

- traceback: prints out the function call stack after an error occurs. does nothing if there is no error.
- debug: flags a function for a "debug" mode which allows you to step through execution of a function one line at the time.
- browser: 
- trace: allows you to insert debuggin code into a function a specific place
- recover: 

### Using the tools

In [41]:
mean(r)
traceback() # Shows you the most recent error

ERROR: Error in mean(r): object 'r' not found


In [42]:
lm(y1 ~ x2)
traceback()

ERROR: Error in eval(expr, envir, enclos): object 'y1' not found


In [43]:
lm(y1 ~ x2)
debug(lm)

ERROR: Error in eval(expr, envir, enclos): object 'y1' not found


In [44]:
double <- function(x) return(x1**2)

addtwo <- function(x, y) {
    z <- x + 2*double(y)
    result <- x. + y
    return(result)
} 

In [45]:
debug(addtwo)
addtwo(1, 2) # Will find the first error in the double function

debugging in: addtwo(1, 2)
debug at <text>#3: {
    z <- x + 2 * double(y)
    result <- x. + y
    return(result)
}
debug at <text>#4: z <- x + 2 * double(y)


ERROR: Error in double(y): object 'x1' not found


In [46]:
options(error = recover)
read.csv("nosuchfile") # Will show where the error happens

Warning message:
In file(file, "rt"): cannot open file 'nosuchfile': No such file or directory

ERROR: Error in file(file, "rt"): cannot open the connection
